# Generated by Django 4.1.6 on 2023-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('valor', models.FloatField(max_length=20)),
            ],
        ),
    ]
